/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAddExpenseRouteImport } from './routes/_authenticated/add-expense'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedCreateGroupRouteImport } from './routes/_authenticated/create-group'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedScoreRouteImport } from './routes/_authenticated/score'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedWalletAccountsRouteImport } from './routes/_authenticated/wallet-accounts'
import { Route as AuthenticatedWalletAddRouteImport } from './routes/_authenticated/wallet-add'
import { Route as AuthenticatedWalletSendRouteImport } from './routes/_authenticated/wallet-send'
import { Route as AuthenticatedWalletWithdrawRouteImport } from './routes/_authenticated/wallet-withdraw'
import { Route as AuthenticatedContributeGroupIdRouteImport } from './routes/_authenticated/contribute.$groupId'
import { Route as AuthenticatedEditGroupGroupIdRouteImport } from './routes/_authenticated/edit-group.$groupId'
import { Route as AuthenticatedExpenseExpenseIdRouteImport } from './routes/_authenticated/expense.$expenseId'
import { Route as AuthenticatedFundingNewGroupIdRouteImport } from './routes/_authenticated/funding-new.$groupId'
import { Route as AuthenticatedGroupGroupIdRouteImport } from './routes/_authenticated/group.$groupId'
import { Route as AuthenticatedInviteGroupIdRouteImport } from './routes/_authenticated/invite.$groupId'
import { Route as AuthenticatedJoinCodeRouteImport } from './routes/_authenticated/join.$code'
import { Route as AuthenticatedSettleGroupIdRouteImport } from './routes/_authenticated/settle.$groupId'
import { Route as AuthenticatedWalletOutGroupIdRouteImport } from './routes/_authenticated/wallet-out.$groupId'
import { Route as AuthenticatedFundingGroupIdRequestIdRouteImport } from './routes/_authenticated/funding.$groupId.$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddExpenseRoute = AuthenticatedAddExpenseRouteImport.update({
  id: '/add-expense',
  path: '/add-expense',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateGroupRoute =
  AuthenticatedCreateGroupRouteImport.update({
    id: '/create-group',
    path: '/create-group',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScoreRoute = AuthenticatedScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletAccountsRoute =
  AuthenticatedWalletAccountsRouteImport.update({
    id: '/wallet-accounts',
    path: '/wallet-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletAddRoute = AuthenticatedWalletAddRouteImport.update({
  id: '/wallet-add',
  path: '/wallet-add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletSendRoute = AuthenticatedWalletSendRouteImport.update({
  id: '/wallet-send',
  path: '/wallet-send',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletWithdrawRoute =
  AuthenticatedWalletWithdrawRouteImport.update({
    id: '/wallet-withdraw',
    path: '/wallet-withdraw',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContributeGroupIdRoute =
  AuthenticatedContributeGroupIdRouteImport.update({
    id: '/contribute/$groupId',
    path: '/contribute/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditGroupGroupIdRoute =
  AuthenticatedEditGroupGroupIdRouteImport.update({
    id: '/edit-group/$groupId',
    path: '/edit-group/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpenseExpenseIdRoute =
  AuthenticatedExpenseExpenseIdRouteImport.update({
    id: '/expense/$expenseId',
    path: '/expense/$expenseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundingNewGroupIdRoute =
  AuthenticatedFundingNewGroupIdRouteImport.update({
    id: '/funding-new/$groupId',
    path: '/funding-new/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupGroupIdRoute =
  AuthenticatedGroupGroupIdRouteImport.update({
    id: '/group/$groupId',
    path: '/group/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInviteGroupIdRoute =
  AuthenticatedInviteGroupIdRouteImport.update({
    id: '/invite/$groupId',
    path: '/invite/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJoinCodeRoute = AuthenticatedJoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettleGroupIdRoute =
  AuthenticatedSettleGroupIdRouteImport.update({
    id: '/settle/$groupId',
    path: '/settle/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletOutGroupIdRoute =
  AuthenticatedWalletOutGroupIdRouteImport.update({
    id: '/wallet-out/$groupId',
    path: '/wallet-out/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundingGroupIdRequestIdRoute =
  AuthenticatedFundingGroupIdRequestIdRouteImport.update({
    id: '/funding/$groupId/$requestId',
    path: '/funding/$groupId/$requestId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/add-expense': typeof AuthenticatedAddExpenseRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/create-group': typeof AuthenticatedCreateGroupRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/score': typeof AuthenticatedScoreRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/wallet-accounts': typeof AuthenticatedWalletAccountsRoute
  '/wallet-add': typeof AuthenticatedWalletAddRoute
  '/wallet-send': typeof AuthenticatedWalletSendRoute
  '/wallet-withdraw': typeof AuthenticatedWalletWithdrawRoute
  '/contribute/$groupId': typeof AuthenticatedContributeGroupIdRoute
  '/edit-group/$groupId': typeof AuthenticatedEditGroupGroupIdRoute
  '/expense/$expenseId': typeof AuthenticatedExpenseExpenseIdRoute
  '/funding-new/$groupId': typeof AuthenticatedFundingNewGroupIdRoute
  '/group/$groupId': typeof AuthenticatedGroupGroupIdRoute
  '/invite/$groupId': typeof AuthenticatedInviteGroupIdRoute
  '/join/$code': typeof AuthenticatedJoinCodeRoute
  '/settle/$groupId': typeof AuthenticatedSettleGroupIdRoute
  '/wallet-out/$groupId': typeof AuthenticatedWalletOutGroupIdRoute
  '/funding/$groupId/$requestId': typeof AuthenticatedFundingGroupIdRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/add-expense': typeof AuthenticatedAddExpenseRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/create-group': typeof AuthenticatedCreateGroupRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/score': typeof AuthenticatedScoreRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/wallet-accounts': typeof AuthenticatedWalletAccountsRoute
  '/wallet-add': typeof AuthenticatedWalletAddRoute
  '/wallet-send': typeof AuthenticatedWalletSendRoute
  '/wallet-withdraw': typeof AuthenticatedWalletWithdrawRoute
  '/contribute/$groupId': typeof AuthenticatedContributeGroupIdRoute
  '/edit-group/$groupId': typeof AuthenticatedEditGroupGroupIdRoute
  '/expense/$expenseId': typeof AuthenticatedExpenseExpenseIdRoute
  '/funding-new/$groupId': typeof AuthenticatedFundingNewGroupIdRoute
  '/group/$groupId': typeof AuthenticatedGroupGroupIdRoute
  '/invite/$groupId': typeof AuthenticatedInviteGroupIdRoute
  '/join/$code': typeof AuthenticatedJoinCodeRoute
  '/settle/$groupId': typeof AuthenticatedSettleGroupIdRoute
  '/wallet-out/$groupId': typeof AuthenticatedWalletOutGroupIdRoute
  '/funding/$groupId/$requestId': typeof AuthenticatedFundingGroupIdRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/add-expense': typeof AuthenticatedAddExpenseRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/create-group': typeof AuthenticatedCreateGroupRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/score': typeof AuthenticatedScoreRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/wallet-accounts': typeof AuthenticatedWalletAccountsRoute
  '/_authenticated/wallet-add': typeof AuthenticatedWalletAddRoute
  '/_authenticated/wallet-send': typeof AuthenticatedWalletSendRoute
  '/_authenticated/wallet-withdraw': typeof AuthenticatedWalletWithdrawRoute
  '/_authenticated/contribute/$groupId': typeof AuthenticatedContributeGroupIdRoute
  '/_authenticated/edit-group/$groupId': typeof AuthenticatedEditGroupGroupIdRoute
  '/_authenticated/expense/$expenseId': typeof AuthenticatedExpenseExpenseIdRoute
  '/_authenticated/funding-new/$groupId': typeof AuthenticatedFundingNewGroupIdRoute
  '/_authenticated/group/$groupId': typeof AuthenticatedGroupGroupIdRoute
  '/_authenticated/invite/$groupId': typeof AuthenticatedInviteGroupIdRoute
  '/_authenticated/join/$code': typeof AuthenticatedJoinCodeRoute
  '/_authenticated/settle/$groupId': typeof AuthenticatedSettleGroupIdRoute
  '/_authenticated/wallet-out/$groupId': typeof AuthenticatedWalletOutGroupIdRoute
  '/_authenticated/funding/$groupId/$requestId': typeof AuthenticatedFundingGroupIdRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/add-expense'
    | '/archive'
    | '/create-group'
    | '/groups'
    | '/history'
    | '/home'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/score'
    | '/wallet'
    | '/wallet-accounts'
    | '/wallet-add'
    | '/wallet-send'
    | '/wallet-withdraw'
    | '/contribute/$groupId'
    | '/edit-group/$groupId'
    | '/expense/$expenseId'
    | '/funding-new/$groupId'
    | '/group/$groupId'
    | '/invite/$groupId'
    | '/join/$code'
    | '/settle/$groupId'
    | '/wallet-out/$groupId'
    | '/funding/$groupId/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/add-expense'
    | '/archive'
    | '/create-group'
    | '/groups'
    | '/history'
    | '/home'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/score'
    | '/wallet'
    | '/wallet-accounts'
    | '/wallet-add'
    | '/wallet-send'
    | '/wallet-withdraw'
    | '/contribute/$groupId'
    | '/edit-group/$groupId'
    | '/expense/$expenseId'
    | '/funding-new/$groupId'
    | '/group/$groupId'
    | '/invite/$groupId'
    | '/join/$code'
    | '/settle/$groupId'
    | '/wallet-out/$groupId'
    | '/funding/$groupId/$requestId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/add-expense'
    | '/_authenticated/archive'
    | '/_authenticated/create-group'
    | '/_authenticated/groups'
    | '/_authenticated/history'
    | '/_authenticated/home'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/score'
    | '/_authenticated/wallet'
    | '/_authenticated/wallet-accounts'
    | '/_authenticated/wallet-add'
    | '/_authenticated/wallet-send'
    | '/_authenticated/wallet-withdraw'
    | '/_authenticated/contribute/$groupId'
    | '/_authenticated/edit-group/$groupId'
    | '/_authenticated/expense/$expenseId'
    | '/_authenticated/funding-new/$groupId'
    | '/_authenticated/group/$groupId'
    | '/_authenticated/invite/$groupId'
    | '/_authenticated/join/$code'
    | '/_authenticated/settle/$groupId'
    | '/_authenticated/wallet-out/$groupId'
    | '/_authenticated/funding/$groupId/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/add-expense': {
      id: '/_authenticated/add-expense'
      path: '/add-expense'
      fullPath: '/add-expense'
      preLoaderRoute: typeof AuthenticatedAddExpenseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-group': {
      id: '/_authenticated/create-group'
      path: '/create-group'
      fullPath: '/create-group'
      preLoaderRoute: typeof AuthenticatedCreateGroupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/score': {
      id: '/_authenticated/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof AuthenticatedScoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet-accounts': {
      id: '/_authenticated/wallet-accounts'
      path: '/wallet-accounts'
      fullPath: '/wallet-accounts'
      preLoaderRoute: typeof AuthenticatedWalletAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet-add': {
      id: '/_authenticated/wallet-add'
      path: '/wallet-add'
      fullPath: '/wallet-add'
      preLoaderRoute: typeof AuthenticatedWalletAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet-send': {
      id: '/_authenticated/wallet-send'
      path: '/wallet-send'
      fullPath: '/wallet-send'
      preLoaderRoute: typeof AuthenticatedWalletSendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet-withdraw': {
      id: '/_authenticated/wallet-withdraw'
      path: '/wallet-withdraw'
      fullPath: '/wallet-withdraw'
      preLoaderRoute: typeof AuthenticatedWalletWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contribute/$groupId': {
      id: '/_authenticated/contribute/$groupId'
      path: '/contribute/$groupId'
      fullPath: '/contribute/$groupId'
      preLoaderRoute: typeof AuthenticatedContributeGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edit-group/$groupId': {
      id: '/_authenticated/edit-group/$groupId'
      path: '/edit-group/$groupId'
      fullPath: '/edit-group/$groupId'
      preLoaderRoute: typeof AuthenticatedEditGroupGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expense/$expenseId': {
      id: '/_authenticated/expense/$expenseId'
      path: '/expense/$expenseId'
      fullPath: '/expense/$expenseId'
      preLoaderRoute: typeof AuthenticatedExpenseExpenseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funding-new/$groupId': {
      id: '/_authenticated/funding-new/$groupId'
      path: '/funding-new/$groupId'
      fullPath: '/funding-new/$groupId'
      preLoaderRoute: typeof AuthenticatedFundingNewGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/group/$groupId': {
      id: '/_authenticated/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite/$groupId': {
      id: '/_authenticated/invite/$groupId'
      path: '/invite/$groupId'
      fullPath: '/invite/$groupId'
      preLoaderRoute: typeof AuthenticatedInviteGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/join/$code': {
      id: '/_authenticated/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof AuthenticatedJoinCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settle/$groupId': {
      id: '/_authenticated/settle/$groupId'
      path: '/settle/$groupId'
      fullPath: '/settle/$groupId'
      preLoaderRoute: typeof AuthenticatedSettleGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet-out/$groupId': {
      id: '/_authenticated/wallet-out/$groupId'
      path: '/wallet-out/$groupId'
      fullPath: '/wallet-out/$groupId'
      preLoaderRoute: typeof AuthenticatedWalletOutGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funding/$groupId/$requestId': {
      id: '/_authenticated/funding/$groupId/$requestId'
      path: '/funding/$groupId/$requestId'
      fullPath: '/funding/$groupId/$requestId'
      preLoaderRoute: typeof AuthenticatedFundingGroupIdRequestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAddExpenseRoute: typeof AuthenticatedAddExpenseRoute
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedCreateGroupRoute: typeof AuthenticatedCreateGroupRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScoreRoute: typeof AuthenticatedScoreRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWalletAccountsRoute: typeof AuthenticatedWalletAccountsRoute
  AuthenticatedWalletAddRoute: typeof AuthenticatedWalletAddRoute
  AuthenticatedWalletSendRoute: typeof AuthenticatedWalletSendRoute
  AuthenticatedWalletWithdrawRoute: typeof AuthenticatedWalletWithdrawRoute
  AuthenticatedContributeGroupIdRoute: typeof AuthenticatedContributeGroupIdRoute
  AuthenticatedEditGroupGroupIdRoute: typeof AuthenticatedEditGroupGroupIdRoute
  AuthenticatedExpenseExpenseIdRoute: typeof AuthenticatedExpenseExpenseIdRoute
  AuthenticatedFundingNewGroupIdRoute: typeof AuthenticatedFundingNewGroupIdRoute
  AuthenticatedGroupGroupIdRoute: typeof AuthenticatedGroupGroupIdRoute
  AuthenticatedInviteGroupIdRoute: typeof AuthenticatedInviteGroupIdRoute
  AuthenticatedJoinCodeRoute: typeof AuthenticatedJoinCodeRoute
  AuthenticatedSettleGroupIdRoute: typeof AuthenticatedSettleGroupIdRoute
  AuthenticatedWalletOutGroupIdRoute: typeof AuthenticatedWalletOutGroupIdRoute
  AuthenticatedFundingGroupIdRequestIdRoute: typeof AuthenticatedFundingGroupIdRequestIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAddExpenseRoute: AuthenticatedAddExpenseRoute,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedCreateGroupRoute: AuthenticatedCreateGroupRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScoreRoute: AuthenticatedScoreRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWalletAccountsRoute: AuthenticatedWalletAccountsRoute,
  AuthenticatedWalletAddRoute: AuthenticatedWalletAddRoute,
  AuthenticatedWalletSendRoute: AuthenticatedWalletSendRoute,
  AuthenticatedWalletWithdrawRoute: AuthenticatedWalletWithdrawRoute,
  AuthenticatedContributeGroupIdRoute: AuthenticatedContributeGroupIdRoute,
  AuthenticatedEditGroupGroupIdRoute: AuthenticatedEditGroupGroupIdRoute,
  AuthenticatedExpenseExpenseIdRoute: AuthenticatedExpenseExpenseIdRoute,
  AuthenticatedFundingNewGroupIdRoute: AuthenticatedFundingNewGroupIdRoute,
  AuthenticatedGroupGroupIdRoute: AuthenticatedGroupGroupIdRoute,
  AuthenticatedInviteGroupIdRoute: AuthenticatedInviteGroupIdRoute,
  AuthenticatedJoinCodeRoute: AuthenticatedJoinCodeRoute,
  AuthenticatedSettleGroupIdRoute: AuthenticatedSettleGroupIdRoute,
  AuthenticatedWalletOutGroupIdRoute: AuthenticatedWalletOutGroupIdRoute,
  AuthenticatedFundingGroupIdRequestIdRoute:
    AuthenticatedFundingGroupIdRequestIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
